Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2020-04, with the labels that each got.

#119 fix: lets populate the github secret if vault
  jxboot-helmfile-resources/templates/gh-secret.yaml
Labels: approved, size/XS

#124 fix: always quote the docker registry org
  jxboot-helmfile-resources/templates/environments.yaml
Labels: approved, size/XS

#143 fix: use the correct version stream YAML
  jxboot-helmfile-resources/templates/environments.yaml
Labels: approved, lgtm, size/XS

#144 fix: use correct YAML for environment version stream
  jxboot-helmfile-resources/templates/environments.yaml
Labels: approved, lgtm, size/XS

#146 fix use correct case of Environment build pack URL
  jxboot-helmfile-resources/templates/environments.yaml
Labels: approved, size/XS

#151 feat: add option to have one certificate per ingress
  jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
  jxboot-helmfile-resources/templates/700-docker-ing.yaml
  jxboot-helmfile-resources/templates/700-hook-ing.yaml
  jxboot-helmfile-resources/templates/700-nexus-ing.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, size/M

#155 fix: add a home link
  jxboot-helmfile-resources/Chart.yaml
Labels: approved, lgtm, size/XS

#158 fix: add a missing label
  jxboot-helmfile-resources/templates/upgrade-cj.yaml
Labels: approved, lgtm, size/XS
