Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2020-12, with the labels that each got.

#317 refactor: work with new jx3 requirements yaml
  jxboot-helmfile-resources/templates/environments.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, size/S

#318 fix: removed old resources no longer used
  jxboot-helmfile-resources/templates/gh-secret.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, size/XXL

#319 chore: include docker.registry.org
  jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
Labels: approved, size/XS

#323 fix: make hook ingress work with istio
  jxboot-helmfile-resources/templates/700-hook-ing.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#321 feat: added in kapp configmap to define custom rules
  jxboot-helmfile-resources/templates/kapp-config.yaml
Labels: approved, lgtm, ok-to-test, size/S
