Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2020-03, with the labels that each got.

#71 fix: avoid hard coded namespace
  jxboot-helmfile-resources/templates/jx-pipeline-activity-reporter-role.yaml
Labels: approved, size/XS

#88 fix: allow roles for other resources
  jxboot-helmfile-resources/templates/committer-role.yaml
  jxboot-helmfile-resources/templates/owner-role.yaml
  jxboot-helmfile-resources/templates/viewer-role.yaml
Labels: approved, lgtm, size/M

#93 fix: switched to the jxl image
  jxboot-helmfile-resources/values.yaml
Labels: approved, size/S

#110 fix: avoid namespace in the path
  jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
  jxboot-helmfile-resources/templates/700-docker-ing.yaml
  jxboot-helmfile-resources/templates/700-hook-ing.yaml
  jxboot-helmfile-resources/templates/700-nexus-ing.yaml
Labels: approved, size/S

#109 fix: mount jenkins-docker-cfg to push images to AWS ECR
  jxboot-helmfile-resources/templates/jenkins-x-pod-templates.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#112 fix: avoid using blank default jxRequirements.ingress.tls.secretName
  jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
  jxboot-helmfile-resources/templates/700-docker-ing.yaml
  jxboot-helmfile-resources/templates/700-hook-ing.yaml
  jxboot-helmfile-resources/templates/700-nexus-ing.yaml
Labels: approved, lgtm, ok-to-test, size/S
