Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2020-02, with the labels that each got.

#24 fix: add local secrets as a k8s Secret
  jxboot-helmfile-resources/templates/local-secrets.yaml
  tests/test_data/custom-env/expected/v1/Secret/jx-local-secrets.yaml
  tests/test_data/default/expected/v1/Secret/jx-local-secrets.yaml
  tests/test_data/no-envs/expected/v1/Secret/jx-local-secrets.yaml
  tests/test_data/remote-env/expected/v1/Secret/jx-local-secrets.yaml
Labels: approved, lgtm, size/M

#43 fix: remove old Jenkins related config so that kaniko can use workloa…
  jxboot-helmfile-resources/values.yaml
Labels: approved, size/L

#45 chore: bump wip go builder image which includes a custom jx built from the multicluster branch
  jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#51 fix: upgrade to the labs build pack
  jxboot-helmfile-resources/templates/jx-pipeline-activity-reporter-role.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, size/S
