Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2021-04, with the labels that each got.

#343 fix: add better upgrade CronJob
  charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/M

#344 fix: add auto merge flag
  charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#345 fix: upgrade updatebot
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#346 fix: add secret copy before running upgrade
  charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/S

#347 fix: upgrade jx and updatebot
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#348 fix: latest updatebot and avoid env var
  charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#349 chore: upgrade updatebot
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#350 fix: upgrade updatebot
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#352 fix: set startingDeadlineSeconds to jobs not scheduling
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Labels: approved, lgtm, ok-to-test, size/XS
