Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2021-05, with the labels that each got.

#353 chore: upgrade versions
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/XS

#355 fix: add optional image pull secrets on the tekton SA
  charts/jxboot-helmfile-resources/templates/build-bot-serviceaccount.yaml
  charts/jxboot-helmfile-resources/values.yaml
  tests/test_data/image-pull-secrets/expected/batch/v1beta1/CronJob/jx-gcactivities.yaml
  tests/test_data/image-pull-secrets/expected/batch/v1beta1/CronJob/jx-gcpods.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/Environment/dev.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/Environment/production.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/Environment/staging.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/SourceRepository/dev.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/SourceRepository/production.yaml
  tests/test_data/image-pull-secrets/expected/jenkins.io/v1/SourceRepository/staging.yaml
  tests/test_data/image-pull-secrets/expected/networking.k8s.io/v1beta1/Ingress/chartmuseum.yaml
  tests/test_data/image-pull-secrets/expected/networking.k8s.io/v1beta1/Ingress/hook.yaml
  tests/test_data/image-pull-secrets/expected/networking.k8s.io/v1beta1/Ingress/nexus.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/ClusterRole/jenkinsx-aggregate-view.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/ClusterRole/tekton-bot.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/ClusterRoleBinding/tekton-bot-jx.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/committer.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/gcactivities.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/gcpods.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/jx-pipeline-activity-updater.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/jx-view.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/owner.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/tekton-bot.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/Role/viewer.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/RoleBinding/gcactivities.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/RoleBinding/gcpods.yaml
  tests/test_data/image-pull-secrets/expected/rbac.authorization.k8s.io/v1/RoleBinding/tekton-bot.yaml
  tests/test_data/image-pull-secrets/expected/v1/ConfigMap/ingress-config.yaml
  tests/test_data/image-pull-secrets/expected/v1/ConfigMap/jenkins-x-docker-registry.yaml
  tests/test_data/image-pull-secrets/expected/v1/ConfigMap/jenkins-x-extensions.yaml
  tests/test_data/image-pull-secrets/expected/v1/ConfigMap/kapp-config.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/jenkins-maven-settings.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/jx-basic-auth-htpasswd.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/jx-basic-auth-user-password.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/jx-local-secrets.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/tekton-container-registry-auth.yaml
  tests/test_data/image-pull-secrets/expected/v1/Secret/tekton-git.yaml
  tests/test_data/image-pull-secrets/expected/v1/ServiceAccount/jx-gcactivities.yaml
  tests/test_data/image-pull-secrets/expected/v1/ServiceAccount/jx-gcpods.yaml
  tests/test_data/image-pull-secrets/expected/v1/ServiceAccount/tekton-bot.yaml
  tests/test_data/image-pull-secrets/values/jxRequirements.values.yaml
Labels: approved, size/XL

#356 fix: give list and delete access to lhjobs
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-role.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS
