Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2021-01, with the labels that each got.

#324 feat: shared istio gateway with tls support
  jxboot-helmfile-resources/templates/600-istio-gateway.yaml
  jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
  jxboot-helmfile-resources/templates/700-bucketrepo-vs.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-vs.yaml
  jxboot-helmfile-resources/templates/700-docker-ing.yaml
  jxboot-helmfile-resources/templates/700-docker-vs.yaml
  jxboot-helmfile-resources/templates/700-hook-ing.yaml
  jxboot-helmfile-resources/templates/700-hook-vs.yaml
  jxboot-helmfile-resources/templates/700-nexus-ing.yaml
  jxboot-helmfile-resources/templates/700-nexus-vs.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/L

#326 fix: remove old resources
  jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
  jxboot-helmfile-resources/templates/jenkins-x-devpod-config.yaml
  tests/test_data/bitbucketserver/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/bitbucketserver/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/custom-env/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/custom-env/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/custom-ingress-host/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/custom-ingress-host/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/custom-ingress-secret/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/custom-ingress-secret/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/default/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/default/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/gitlab/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/gitlab/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/gke-domain-bucketrepo/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/gke-domain-bucketrepo/expected/v1/ConfigMap/jenkins-x-docker-registry.yaml
  tests/test_data/gke-domain-bucketrepo/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/gke-domain-bucketrepo/values/jxRequirements.values.yaml
  tests/test_data/gke-domain/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/gke-domain/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/gke/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/gke/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/istio/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/istio/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/lighthouse-jx/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/lighthouse-jx/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/lighthouse-tekton/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/lighthouse-tekton/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/no-envs/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/no-envs/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/nodeport/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/nodeport/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/private-repo/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/private-repo/expected/v1/Secret/jenkins-docker-cfg.yaml
  tests/test_data/remote-env/expected/v1/ConfigMap/jenkins-x-devpod-config.yaml
  tests/test_data/remote-env/expected/v1/Secret/jenkins-docker-cfg.yaml
Labels: approved, size/L

#327 feat: allow user to provide gateway name or create gateway
  jxboot-helmfile-resources/templates/600-istio-gateway.yaml
  jxboot-helmfile-resources/templates/700-bucketrepo-vs.yaml
  jxboot-helmfile-resources/templates/700-chartmuseum-vs.yaml
  jxboot-helmfile-resources/templates/700-docker-vs.yaml
  jxboot-helmfile-resources/templates/700-hook-vs.yaml
  jxboot-helmfile-resources/templates/700-nexus-vs.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#328 feat: global pipeline variables
  jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
  jxboot-helmfile-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/S
