Repository jenkins-x-charts/jxboot-helmfile-resources, pull requests merged in 2021-03, with the labels that each got.

#334 fix: move to charts folder
  charts/jxboot-helmfile-resources/.gitignore
  charts/jxboot-helmfile-resources/Chart.yaml
  charts/jxboot-helmfile-resources/README.md
  charts/jxboot-helmfile-resources/requirements.yaml
  charts/jxboot-helmfile-resources/templates/600-istio-gateway.yaml
  charts/jxboot-helmfile-resources/templates/700-bucketrepo-ing.yaml
  charts/jxboot-helmfile-resources/templates/700-bucketrepo-vs.yaml
  charts/jxboot-helmfile-resources/templates/700-chartmuseum-ing.yaml
  charts/jxboot-helmfile-resources/templates/700-chartmuseum-vs.yaml
  charts/jxboot-helmfile-resources/templates/700-docker-ing.yaml
  charts/jxboot-helmfile-resources/templates/700-docker-vs.yaml
  charts/jxboot-helmfile-resources/templates/700-hook-ing.yaml
  charts/jxboot-helmfile-resources/templates/700-hook-vs.yaml
  charts/jxboot-helmfile-resources/templates/700-nexus-ing.yaml
  charts/jxboot-helmfile-resources/templates/700-nexus-vs.yaml
  charts/jxboot-helmfile-resources/templates/_helpers.tpl
  charts/jxboot-helmfile-resources/templates/build-bot-clusterrole.yaml
  charts/jxboot-helmfile-resources/templates/build-bot-clusterrolebinding.yaml
  charts/jxboot-helmfile-resources/templates/build-bot-role.yaml
  charts/jxboot-helmfile-resources/templates/build-bot-rolebinding.yaml
  charts/jxboot-helmfile-resources/templates/build-bot-serviceaccount.yaml
  charts/jxboot-helmfile-resources/templates/chartmuseum-link-secret.yaml
  charts/jxboot-helmfile-resources/templates/chartmuseum-link-service.yaml
  charts/jxboot-helmfile-resources/templates/committer-role.yaml
  charts/jxboot-helmfile-resources/templates/core-chartmuseum-secret.yaml
  charts/jxboot-helmfile-resources/templates/environments.yaml
  charts/jxboot-helmfile-resources/templates/featureflag-secret.yaml
  charts/jxboot-helmfile-resources/templates/ingress-config-configmap.yaml
  charts/jxboot-helmfile-resources/templates/jenkins-x-aggregate-view.yaml
  charts/jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
  charts/jxboot-helmfile-resources/templates/jenkins-x-extensions-config.yaml
  charts/jxboot-helmfile-resources/templates/jx-basic-auth-htpasswd-secret.yaml
  charts/jxboot-helmfile-resources/templates/jx-basic-auth-user-password-secret.yaml
  charts/jxboot-helmfile-resources/templates/jx-pipeline-activity-reporter-role.yaml
  charts/jxboot-helmfile-resources/templates/jx-view-role.yaml
  charts/jxboot-helmfile-resources/templates/kaniko-secret.yaml
  charts/jxboot-helmfile-resources/templates/kapp-config.yaml
  charts/jxboot-helmfile-resources/templates/local-secrets.yaml
  charts/jxboot-helmfile-resources/templates/maven-settings-secret.yaml
  charts/jxboot-helmfile-resources/templates/nexus-link-service.yaml
  charts/jxboot-helmfile-resources/templates/npm-token-secret.yaml
  charts/jxboot-helmfile-resources/templates/owner-role.yaml
  charts/jxboot-helmfile-resources/templates/release-gpg-secret.yaml
  charts/jxboot-helmfile-resources/templates/repositories.yaml
  charts/jxboot-helmfile-resources/templates/tekton-artifact-bucket-secret.yaml
  charts/jxboot-helmfile-resources/templates/tekton-container-registry-auth-secret.yaml
  charts/jxboot-helmfile-resources/templates/tekton-git-secret.yaml
  charts/jxboot-helmfile-resources/templates/upgrade-cj.yaml
  charts/jxboot-helmfile-resources/templates/viewer-role.yaml
  charts/jxboot-helmfile-resources/values.yaml
  tests/chart_test.go
Labels: approved, size/XS

#336 fix: try release to the bucket
  .lighthouse/jenkins-x/release.yaml
  charts/jxboot-helmfile-resources/Makefile
Labels: approved, size/M

#337 fix: switch to the jx3 repo
  charts/jxboot-helmfile-resources/Makefile
Labels: approved, size/XS

#338 fix: add new GC jobs
  charts/jxboot-helmfile-resources/requirements.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-rb.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-role.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-sa.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-rb.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-role.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-sa.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/L

#339 fix: use correct command line
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Labels: approved, size/XS

#340 fix: flags
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Labels: approved, size/XS

#341 fix: disable gpg secret by default
  charts/jxboot-helmfile-resources/templates/release-gpg-secret.yaml
  charts/jxboot-helmfile-resources/values.yaml
Labels: approved, size/S

#342 fix: allow annotations for gc job pods again
  charts/jxboot-helmfile-resources/templates/jx-gcactivities-cronjob.yaml
  charts/jxboot-helmfile-resources/templates/jx-gcpods-cronjob.yaml
Labels: approved, lgtm, ok-to-test, size/XS
